const images = {
  booktogothumb: "/images/projects/BookToGo.lk/thumb.png",
  booktogo1: "/images/projects/BookToGo.lk/1.jpeg",
  booktogo2: "/images/projects/BookToGo.lk/2.jpeg",
    booktogo3: "/images/projects/BookToGo.lk/3.jpeg",
    booktogo4: "/images/projects/BookToGo.lk/4.jpeg",
    booktogo5: "/images/projects/BookToGo.lk/5.jpeg",
    booktogo6: "/images/projects/BookToGo.lk/6.jpeg",
    booktogo7: "/images/projects/BookToGo.lk/7.jpeg",
    booktogo8: "/images/projects/BookToGo.lk/8.jpeg",
    booktogo9: "/images/projects/BookToGo.lk/9.jpeg",
    booktogo10: "/images/projects/BookToGo.lk/10.jpeg",
    booktogo11: "/images/projects/BookToGo.lk/11.jpeg",
    booktogo12: "/images/projects/BookToGo.lk/12.jpeg",
    booktogo13: "/images/projects/BookToGo.lk/13.jpeg",
    booktogo14: "/images/projects/BookToGo.lk/14.jpeg",
  skillbridgethumb: "/images/projects/SkillBridge/thumb.png",
  sddsthumb: "/images/projects/sdds apo/thumb.png",
  stichingguide: "/images/projects/stitching-guide.jpg",
  skillbridgereact: "/images/projects/SkillBridge/react.png",
  skillbridhenext: "/images/projects/SkillBridge/next.png",
  sk1: "/images/projects/SkillBridge/1.jpg",
  sk2: "/images/projects/SkillBridge/2.jpg",
};

export default images;
