const images = {
  booktogothumb: "/images/projects/BookToGo.lk/thumb.png",
  booktogo1: "/images/projects/BookToGo.lk/1.jpeg",
  booktogo2: "/images/projects/BookToGo.lk/2.jpeg",
  booktogo3: "/images/projects/BookToGo.lk/3.jpeg",
  booktogo4: "/images/projects/BookToGo.lk/4.jpeg",
  booktogo5: "/images/projects/BookToGo.lk/5.png",
  booktogo6: "/images/projects/BookToGo.lk/6.jpeg",
  booktogo7: "/images/projects/BookToGo.lk/7.jpg",
  booktogo8: "/images/projects/BookToGo.lk/8.jpeg",
  booktogo9: "/images/projects/BookToGo.lk/9.jpeg",
  booktogo10: "/images/projects/BookToGo.lk/10.jpeg",
  booktogo11: "/images/projects/BookToGo.lk/11.jpeg",
  booktogo12: "/images/projects/BookToGo.lk/12.jpeg",
  booktogo13: "/images/projects/BookToGo.lk/13.jpeg",
  booktogo14: "/images/projects/BookToGo.lk/14.jpeg",
  skillbridgethumb: "/images/projects/SkillBridge/thumb.png",

  stichingguide: "/images/projects/stitching-guide.jpg",
  stitchingthumb: "/images/projects/stitching guide/thumb.png",
  stitching1: "/images/projects/stitching guide/1.jpg",
  stitching2: "/images/projects/stitching guide/2.jpg",
  stitching3: "/images/projects/stitching guide/3.jpg",
  stitching4: "/images/projects/stitching guide/4.jpg",
    stitching5: "/images/projects/stitching guide/5.jpg",
    stitching6: "/images/projects/stitching guide/6.jpg",
    stitching7: "/images/projects/stitching guide/7.jpg",

  skillbridgereact: "/images/projects/SkillBridge/react.png",
  skillbridhenext: "/images/projects/SkillBridge/next.png" ,
  sk1: "/images/projects/SkillBridge/1.jpg",
  sk2: "/images/projects/SkillBridge/2.jpg",
  sk3: "/images/projects/SkillBridge/3.jpg",
  sk4: "/images/projects/SkillBridge/4.jpg",
  sk5: "/images/projects/SkillBridge/5.jpg",
  sk6: "/images/projects/SkillBridge/6.jpg",
  sk7: "/images/projects/SkillBridge/7.jpg",
  sk8: "/images/projects/SkillBridge/8.jpg",
  sk9: "/images/projects/SkillBridge/9.jpg",
  sk10: "/images/projects/SkillBridge/10.jpg",
  sk11: "/images/projects/SkillBridge/11.jpg",
  sk12: "/images/projects/SkillBridge/12.jpg",
  sk13: "/images/projects/SkillBridge/13.jpg",
  sk14: "/images/projects/SkillBridge/14.jpg",
  sk15: "/images/projects/SkillBridge/15.jpg",
  sk16: "/images/projects/SkillBridge/16.jpg",

  sddsthumb: "/images/projects/sdds App/thum.png",
  sdds1: "/images/projects/sdds App/1.jpg",
  sdds2: "/images/projects/sdds App/2.jpg",
  sdds3: "/images/projects/sdds App/3.jpg",
  sdds4: "/images/projects/sdds App/4.jpg",
  sdds5: "/images/projects/sdds App/5.jpg",
  sdds6: "/images/projects/sdds App/6.jpg",
  sdds7: "/images/projects/sdds App/7.jpg",
  sdds8: "/images/projects/sdds App/8.jpg",
  sdds9: "/images/projects/sdds App/9.jpg",
  sdds10: "/images/projects/sdds App/10.jpg",
  sdds11: "/images/projects/sdds App/11.jpg",
  sdds12: "/images/projects/sdds App/12.jpg",
  sdds13: "/images/projects/sdds App/13.jpg",
  sdds14: "/images/projects/sdds App/14.jpg",
  sdds15: "/images/projects/sdds App/15.jpg",
  sdds16: "/images/projects/sdds App/16.jpg",
  sdds17: "/images/projects/sdds App/17.jpg",
  sdds18: "/images/projects/sdds App/18.jpg",
  sdds19: "/images/projects/sdds App/19.jpg",
};

export default images;
